version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  enqueuer:
    build:
      context: ./enqueuer
    container_name: enqueuer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ENQUEUER_POOL_SIZE: 100
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"

  dequeuer_nginx:
    build:
      context: ./dequeuer
    container_name: dequeuer_nginx
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DEQUEUER_POOL_SIZE: 100
      SERVICE_NAME: nginx
      DOWNSTREAM_URL: http://nginx:80/
    depends_on:
      - rabbitmq
    ports:
      - "8011:8001"

  dequeuer_google:
    build:
      context: ./dequeuer
    container_name: dequeuer_google
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DEQUEUER_POOL_SIZE: 100
      SERVICE_NAME: google
      DOWNSTREAM_URL: https://google.com
    depends_on:
      - rabbitmq
    ports:
      - "8012:8001"

  url-fetcher:
    build:
      context: ./url-fetcher
    container_name: url-fetcher
    environment:
      BATCH_SIZE: 100
    ports:
      - "8001:8000"

  dequeuer_url_fetcher:
    build:
      context: ./dequeuer
    container_name: dequeuer_url_fetcher
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DEQUEUER_POOL_SIZE: 100
      SERVICE_NAME: url_fetcher
      BATCH_MODE: true
      DOWNSTREAM_URL: http://url-fetcher:8000/fetch
      BATCH_DOWNSTREAM_URL: http://url-fetcher:8000/fetch/batch
    depends_on:
      - rabbitmq
      - url-fetcher
    ports:
      - "8013:8001"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - enqueuer
      - dequeuer_nginx
      - dequeuer_google
      - dequeuer_url_fetcher

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
