global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'enqueuer'
    static_configs:
      - targets: ['enqueuer:8000']

  - job_name: 'dequeuer_nginx'
    static_configs:
      - targets: ['dequeuer_nginx:8001']

  - job_name: 'dequeuer_google'
    static_configs:
      - targets: ['dequeuer_google:8001']

  - job_name: 'dequeuer_url_fetcher'
    static_configs:
      - targets: ['dequeuer_url_fetcher:8001']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692'] 