apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: proxymq
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: dequeuer
          image: {{ .Values.dequeuer.image }}
          imagePullPolicy: Always  # For local development
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: DEQUEUER_POOL_SIZE
            value: "100"
          - name: SERVICE_NAME
            value: "nginx"
          - name: DOWNSTREAM_URL
            value: "http://localhost:80/"
          - name: HEALTH_CHECK_URL
            value: "http://localhost:80/"
          - name: HEALTH_CHECK_INTERVAL
            value: "5"
          - name: HEALTH_CHECK_TIMEOUT
            value: "10"
          ports:
          - containerPort: 8001
            name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          restartPolicy: Always
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
